### ISSUE TITLE
Absolute url

### ISSUE THREAD

**Issue by vn38minhtran** [haydenbleasel/favicons#103]
```html
<meta property="twitter:image" content="http:/localhost:3000/9aa5cd46d7f431d2838bef208ec125ab.png">
<meta property="og:image" content="http:/localhost:3000/5daf4bea0e3ab132107fa0c27a5dfe52.png">
```
I think url shoud be `http://localhost:3000` instead of `http:/localhost:3000`

**Comment by haydenbleasel** [comment]
I thought this was fixed in #73 / #74. What versions of Favicons / Gulp-Favicons are you using?

**Comment by vn38minhtran** [comment]
You can see more info here.
- Favicons version : https://github.com/vn38minhtran/react-flux-starter/blob/babel5/package.json#L34
- Html : https://github.com/vn38minhtran/react-flux-starter/blob/babel5/app/_favicons.html#L27
- Generate code : https://github.com/vn38minhtran/react-flux-starter/blob/babel5/tasks/build/favicons/generate.js

**Comment by vn38minhtran** [comment]
I think bug come from line:
https://github.com/haydenbleasel/favicons/blob/master/helpers.js#L42.
When call replace it replace `//` by `/`.

**Comment by vn38minhtran** [comment]
```js
...
function relative (directory) {
            return path.join(options.path, directory).replace(/\\/g, '/');
        }

        function absolute (directory) {
            return path.join(options.url, relative(directory));
        }
...
```

**Comment by andrey-hohlov** [comment]
My mistake :(

**Comment by haydenbleasel** [comment]
I think this is also due to `path.join` which is meant to be `url.resolve` (to preserve the double slashes). This keeps reverting in new commits so I'll need to make sure this is fixed.

**Comment by haydenbleasel** [comment]
Fixed in `favicons@4.5.2`

**Comment by jeffreywescott** [comment]
I'm using version `4.8.6` and still seeing this. I'm not using Gulp -- just using the code in my own app directly.

**Comment by jeffreywescott** [comment]
To reproduce, just pass a URL in the `path` option, like this: 'http://example.com'.

**Comment by jeffreywescott** [comment]
Workaround is to use a base URL like this: 'http:\\\\example.com' -- stupid ugly and confusing, but works.
